In [9]:
import pandas as pd 
value = { "Name":["Atharva","Dipti","Omkar","Narayan"],"Age":[22,21,24,19], "Salary":[10000,90000,1912,12721],"Department":["IT","CS","ENTC","IT"]}
df = pd.DataFrame(value)
df

      Name  Age  Salary Department
0  Atharva   22   10000         IT
1    Dipti   21   90000         CS
2    Omkar   24    1912       ENTC
3  Narayan   19   12721         IT

In [ ]:
#All name from the DataFrame 
print(df["Name"])

0    Atharva
1      Dipti
2      Omkar
3    Narayan
Name: Name, dtype: object

In [20]:
# Question:
# You have a DataFrame containing employee details with columns:
# Name, Department, Salary, Age.

# Write code to:

# Display employees whose salary is greater than 100,00.
print("Display employees whose salary is greater than 100,00.\n",df[df["Salary"]>10000])
# Display employees from the IT department.
print("Display employees from the IT department.\n",df[df["Department"]=="IT"])
# Sort the employees by salary in descending order.
print("Sort the employees by salary in descending order.\n",df["Salary"].sort_values(ascending=False).reset_index(drop=True))

Display employees whose salary is greater than 100,00.
       Name  Age  Salary Department
1    Dipti   21   90000         CS
3  Narayan   19   12721         IT
Display employees from the IT department.
       Name  Age  Salary Department
0  Atharva   22   10000         IT
3  Narayan   19   12721         IT
Sort the employees by salary in descending order.
 0    90000
1    12721
2    10000
3     1912
Name: Salary, dtype: int64

In [22]:
# 8 july 
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [23, 30, 22, 28, 35],
    "Salary": [50000, 70000, 45000, 65000, 80000]
}

df = pd.DataFrame(data)
# Tasks
# Display employees whose age is greater than 25.
# Display employees whose salary is at least 65,000.
# Display only the Name and Salary columns for employees older than 25.

age = df[df["Age"]>25]
salary = df[df["Salary"]>=65000]
result = df.loc[df["Age"] > 25, ["Name", "Salary"]]
print("Display employees whose age is greater than 25.",age)
print("Display employees whose salary is at least 65,000.",salary)
print("Display only the Name and Salary columns for employees older than 25.",result)

Display employees whose age is greater than 25.     Name  Age  Salary
1    Bob   30   70000
3  David   28   65000
4    Eva   35   80000
Display employees whose salary is at least 65,000.     Name  Age  Salary
1    Bob   30   70000
3  David   28   65000
4    Eva   35   80000
Display only the Name and Salary columns for employees older than 25.     Name  Salary
1    Bob   70000
3  David   65000
4    Eva   80000

In [38]:
# 9 july  
#  Find the Highest Paid Employee in Each Department
import pandas as pd

data = {
    "Name": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Sneha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Salary": [50000, 45000, 70000, 60000, 55000, 75000]
}

df = pd.DataFrame(data)
# Interview Question

# Find the employee with the highest salary in each department.
df.groupby("Department")[["Salary","Name"]].max()

            Salary   Name
Department
Finance      75000  Sneha
HR           55000   Neha
IT           70000  Rahul

In [45]:
# : Add a New Column
# import pandas as pd

data = {
    "Name": ["Amit", "Neha", "Rahul", "Priya"],
    "Salary": [40000, 60000, 55000, 80000]
}

df = pd.DataFrame(data)

# Create a new column called Bonus.

# If salary is greater than or equal to 60000 → Bonus = 10000
# Otherwise → Bonus = 5000
df["Bonus"] = df["Salary"].apply(lambda x : 10000 if x >= 60000 else 5000)
print(df)

    Name  Salary  Bonus
0   Amit   40000   5000
1   Neha   60000  10000
2  Rahul   55000   5000
3  Priya   80000  10000